requires = ["tox>=4"]
env_list = ["lint", "type", "3.14", "3.13", "3.12"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8",
  "pytest-sugar",
  "coverage",
  "pytest-cov"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.lint]
description = "run linters"
skip_install = true
deps = ["black"]
commands = [["black", { replace = "posargs", default = ["."], extend = true} ]]

# [env.type]
# description = "run type checks"
# deps = ["mypy", "pytest"]
# commands = [["mypy", { replace = "posargs", default = ["src", "tests"], extend = true} ]]
